name: lm_teams_app
description: App for Literature Ministry

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  http: ^1.1.0
  objectid: ^3.0.0
  flutter_secure_storage: ^9.0.0
  web_socket_channel: ^2.3.0
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  select_form_field: ^2.2.0
  image_picker: ^1.0.5
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  path_provider: ^2.0.3
  equatable: ^2.0.3
  formz: ^0.6.1
  cached_network_image: ^3.1.0
  image_cropper: ^5.0.0
  flutter_easyloading: ^3.0.3
  badges: ^3.1.2
  flutter_slidable: ^3.0.1
  getwidget: ^4.0.0
  multi_select_flutter: ^4.0.0
  socket_io_client: ^2.0.0
  flutter_branch_sdk: ^7.0.2
  location: ^5.0.3
  toggle_switch: ^2.0.1
  url_launcher: ^6.0.20
  change_app_package_name: ^1.0.0
  flutter_background_geolocation: ^4.16.4
  syncfusion_flutter_datepicker: ^23.2.4
  jiffy: ^5.0.0
  flutter_countdown_timer: ^4.1.0
  percent_indicator: ^4.0.0
  flutter_services_binding: ^0.1.0
  dropdown_button2: ^2.3.9
  geocoding: ^2.0.5
  flutter_switch: ^0.3.2
  flutter_screenutil: ^5.5.4
  # flutter_local_notifications: ^18.0.1
  timezone: ^0.9.0
  connectivity_plus: ^5.0.2
  restart_app: ^1.1.0
  google_maps_flutter: ^2.4.0
  app_settings: ^5.1.1
  flutter_treeview: ^1.0.7+1
  flutter_staggered_grid_view: ^0.7.0
  intl_phone_number_input: ^0.7.3+1
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design:
    true

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/svg/
    - assets/svgIcons/
    - assets/map_themes/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
